# [9660] Logistic Regression 1
Data file:
* seaborn : iris
#### https://seaborn.pydata.org/generated/seaborn.load_dataset.html

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 10/14/26 18:44:59

### Import libraries

In [2]:
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

#### Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.

In [4]:
import pandas as pd

In [5]:
import statsmodels.formula.api as smf

### Load data

In [6]:
# List available data sets
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [7]:
# Load iris data set
data = sns.load_dataset("iris")

(https://)Independent variables (in centimeters)
* sepal_length
* sepal_width
* petal_length
* petal_width

Dependent variable
* species
  * classes: Setosa, Versicolor, Virginica

* The Iris dataset is one of the most well-known and commonly used datasets in the field of machine learning and statistics. In this article, we will explore the Iris dataset in deep and learn about its uses and applications.

* What is Iris Dataset?The Iris dataset consists of 150 samples of iris flowers from three different species: Setosa, Versicolor, and Virginica. Each sample includes four features: sepal length, sepal width, petal length, and petal width.

### Examine data

In [8]:
data.shape

(150, 5)

In [9]:
# Review data
data.head(51)

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
5            5.4          3.9           1.7          0.4      setosa
6            4.6          3.4           1.4          0.3      setosa
7            5.0          3.4           1.5          0.2      setosa
8            4.4          2.9           1.4          0.2      setosa
9            4.9          3.1           1.5          0.1      setosa
10           5.4          3.7           1.5          0.2      setosa
11           4.8          3.4           1.6          0.2      setosa
12           4.8          3.0           1.4          0.1      setosa
13           4.3          3.0           1.1          0.1      setosa
14           5.8          4.0           1.2          0.2      setosa
15           5.7          4.4           1.5          0.4      setosa
16           5.4          3.9           1.3          0.4      setosa
17           5.1          3.5           1.4          0.3      setosa
18           5.7          3.8           1.7          0.3      setosa
19           5.1          3.8           1.5          0.3      setosa
20           5.4          3.4           1.7          0.2      setosa
21           5.1          3.7           1.5          0.4      setosa
22           4.6          3.6           1.0          0.2      setosa
23           5.1          3.3           1.7          0.5      setosa
24           4.8          3.4           1.9          0.2      setosa
25           5.0          3.0           1.6          0.2      setosa
26           5.0          3.4           1.6          0.4      setosa
27           5.2          3.5           1.5          0.2      setosa
28           5.2          3.4           1.4          0.2      setosa
29           4.7          3.2           1.6          0.2      setosa
30           4.8          3.1           1.6          0.2      setosa
31           5.4          3.4           1.5          0.4      setosa
32           5.2          4.1           1.5          0.1      setosa
33           5.5          4.2           1.4          0.2      setosa
34           4.9          3.1           1.5          0.2      setosa
35           5.0          3.2           1.2          0.2      setosa
36           5.5          3.5           1.3          0.2      setosa
37           4.9          3.6           1.4          0.1      setosa
38           4.4          3.0           1.3          0.2      setosa
39           5.1          3.4           1.5          0.2      setosa
40           5.0          3.5           1.3          0.3      setosa
41           4.5          2.3           1.3          0.3      setosa
42           4.4          3.2           1.3          0.2      setosa
43           5.0          3.5           1.6          0.6      setosa
44           5.1          3.8           1.9          0.4      setosa
45           4.8          3.0           1.4          0.3      setosa
46           5.1          3.8           1.6          0.2      setosa
47           4.6          3.2           1.4          0.2      setosa
48           5.3          3.7           1.5          0.2      setosa
49           5.0          3.3           1.4          0.2      setosa
50           7.0          3.2           4.7          1.4  versicolor

In [10]:
data.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [11]:
# List targets / classes
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
data['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Inference

* Generate Logistic Regression results using all dataset

In [ ]:
### the following code is wrong

In [13]:
model = smf.logit("species~sepal_length+sepal_width+petal_length+petal_width", data=data).fit()

#view model summary
print(model.summary())

ValueError: endog has evaluated to an array with multiple columns that has shape (150, 3). This occurs when the variable converted to endog is non-numeric (e.g., bool or str).

In [ ]:
## The above code is supposed to have error messgaes

In [14]:
# Generate encodings for species
df_ohe1 = pd.get_dummies(data['species'])
df_ohe1.head(100)

    setosa  versicolor  virginica
0     True       False      False
1     True       False      False
2     True       False      False
3     True       False      False
4     True       False      False
..     ...         ...        ...
95   False        True      False
96   False        True      False
97   False        True      False
98   False        True      False
99   False        True      False

[100 rows x 3 columns]

In [ ]:
# convert them into dummies

In [15]:
df_ohe1 = df_ohe1.astype(int)
df_ohe1.head(100)

    setosa  versicolor  virginica
0        1           0          0
1        1           0          0
2        1           0          0
3        1           0          0
4        1           0          0
..     ...         ...        ...
95       0           1          0
96       0           1          0
97       0           1          0
98       0           1          0
99       0           1          0

[100 rows x 3 columns]

In [16]:
# Join dataframe with Gender-encoded dataframe
data1 = data.join(df_ohe1)
data1.head(100)

,sepal_length,sepal_width,petal_length,petal_width,species,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0
...,...,...,...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,versicolor,0,1,0
96,5.7,2.9,4.2,1.3,versicolor,0,1,0
97,6.2,2.9,4.3,1.3,versicolor,0,1,0
98,5.1,2.5,3.0,1.1,versicolor,0,1,0
99,5.7,2.8,4.1,1.3,versicolor,0,1,0

* We need to creat 3 classifier and see how to interpret the results

In [17]:
model = smf.logit("setosa~sepal_length+sepal_width+petal_length+petal_width", data=data1).fit()

#view model summary
print(model.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                 setosa   No. Observations:                  150
Model:                          Logit   Df Residuals:                      145
Method:                           MLE   Df Model:                            4
Date:                Wed, 14 Oct 2026   Pseudo R-squ.:                   1.000
Time:                        18:49:19   Log-Likelihood:            -6.9724e-09
converged:                      False   LL-Null:                       -95.477
Covariance Type:            nonrobust   LLR p-value:                 3.305e-40
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -11.8568   4.64e+05  -2.55e-05      1.000    -9.1e+05     9.1e+05
sepal_length     9.6294   1.21e+05   7.98e-05      1.000   -2.37e+05    2.37e+05
sepal_width      8.4423   5.13e+04      0.000      1.000   -1.01e+05    1.01e+05
petal_length   -20.5324    8.9e+04     -0.000      1.000   -1.75e+05    1.75e+05
petal_width    -14.9497   1.39e+05     -0.000      1.000   -2.72e+05    2.72e+05
================================================================================

Complete Separation: The results show that there iscomplete separation or perfect prediction.
In this case the Maximum Likelihood Estimator does not exist and the parameters
are not identified.

/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Applications/anaconda3/lib/python3.13/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [ ]:
# the results are not good

In [18]:
model = smf.logit("versicolor	~sepal_length+sepal_width+petal_length+petal_width", data=data1).fit()

#view model summary
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.483566
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:             versicolor   No. Observations:                  150
Model:                          Logit   Df Residuals:                      145
Method:                           MLE   Df Model:                            4
Date:                Wed, 14 Oct 2026   Pseudo R-squ.:                  0.2403
Time:                        19:17:52   Log-Likelihood:                -72.535
converged:                       True   LL-Null:                       -95.477
Covariance Type:            nonrobust   LLR p-value:                 2.603e-09
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        7.3785      2.499      2.952      0.003       2.480      12.277
sepal_length    -0.2454      0.650     -0.378      0.706      -1.518       1.028
sepal_width     -2.7966      0.784     -3.569      0.000      -4.332      -1.261
petal_length     1.3136      0.684      1.921      0.055      -0.027       2.654
petal_width     -2.7783      1.173     -2.368      0.018      -5.078      -0.479
================================================================================

* sepal_width will have a negative influence on the probability of being a versicolor
* patal_length will have a positive influence on the probability of being a versicolor
* patal_width will have a negative influence on the probability of being a versicolor

In [19]:
model = smf.logit("virginica	~sepal_length+sepal_width+petal_length+petal_width", data=data1).fit()

#view model summary
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.039662
         Iterations 14
                           Logit Regression Results
==============================================================================
Dep. Variable:              virginica   No. Observations:                  150
Model:                          Logit   Df Residuals:                      145
Method:                           MLE   Df Model:                            4
Date:                Wed, 14 Oct 2026   Pseudo R-squ.:                  0.9377
Time:                        19:21:04   Log-Likelihood:                -5.9493
converged:                       True   LL-Null:                       -95.477
Covariance Type:            nonrobust   LLR p-value:                 1.189e-37
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -42.6378     25.708     -1.659      0.097     -93.024       7.748
sepal_length    -2.4652      2.394     -1.030      0.303      -7.158       2.228
sepal_width     -6.6809      4.480     -1.491      0.136     -15.461       2.099
petal_length     9.4294      4.737      1.990      0.047       0.145      18.714
petal_width     18.2861      9.743      1.877      0.061      -0.809      37.381
================================================================================

Possibly complete quasi-separation: A fraction 0.73 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

* petal_length will have a positive influence on the probability of being a virginica
* petal_width will have a positive influence on the probability of being a virginica




## Prediction

In [20]:
from sklearn.metrics import accuracy_score

### Prepare data

In [21]:
# Prepare data set for training DataFrame.iloc: Purely integer-location based indexing for selection by positio
X = data.iloc[:, :-1]     # feature values - all columns except last one
y = data.iloc[:, -1]      # target values - last column of data frame

In [22]:
# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Train Logistic Regression model

In [23]:
# Train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)
# Look closely at the error message below

LogisticRegression()

In [24]:
# Display model (default) hyperparameters
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'deprecated',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [25]:
# Train the model again
model = LogisticRegression(max_iter = 200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

#### Similar to linear regression, logistic regression calculates intercept and coefficient values
#### For multiclass (more than 2 classes) problems, logistic regression creates N classifiers
For example, in this case where the dataset has 3 classes, sklearn's LogisticRegression:
* creates 3 classifiers, each with their own intercept and set of coefficents
* to make a prediction for a new data point, the decision function is evaluated for each class, and the class with the highest value is chosen as the predicted class

In [26]:
print(f"classes: {model.classes_}\n")
print(f"number of features: {model.n_features_in_}\n")
print(f"features: {model.feature_names_in_}\n")
print(f"intercept: {model.intercept_}\n")
print(f"coefficents: {model.coef_}\n")

classes: ['setosa' 'versicolor' 'virginica']

number of features: 4

features: ['sepal_length' 'sepal_width' 'petal_length' 'petal_width']

intercept: [  9.00942702   1.86870961 -10.87813663]

coefficents: [[-0.39351437  0.96243885 -2.37515412 -0.99875065]
 [ 0.50847025 -0.25478137 -0.21300695 -0.77574601]
 [-0.11495588 -0.70765748  2.58816108  1.77449666]]

### Test model

In [27]:
# Test the model
predictions = model.predict(X_test)

# Print predictions
print(predictions)

['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa']

### Model evaluation

In [28]:
# Check precision, recall and f1-score on the test data
# y_test is the true y on the test dataset, prediction is the predicted y on the test data
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

### Model accuracy

##### There are two ways to calculate the accuracy rate.

In [29]:

print(f"Accuracy = {round((accuracy_score(y_test, predictions) * 100), 4)}%")

Accuracy = 100.0%

In [30]:
accuracy = model.score(X_test, y_test)
print("accuracy =", round((accuracy * 100), 2), "%")

accuracy = 100.0 %